---
# Install AWX Operator tasks
- name: Create temporary directory
  ansible.builtin.file:
    path: "{{ awx_on_k3s_dir }}"
    state: directory
    mode: "0755"

- name: Clone the AWX on K3s repository
  ansible.builtin.git:
    repo: "{{ awx_on_k3s_repo }}"
    dest: "{{ awx_on_k3s_dir }}"
    version: "{{ awx_on_k3s_version }}"
    force: yes

- name: Deploy AWX Operator
  ansible.builtin.shell: |
    kubectl apply -k operator
  args:
    chdir: "{{ awx_on_k3s_dir }}"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Wait for AWX Operator to be ready
  ansible.builtin.shell: |
    kubectl -n awx get pods -l control-plane=controller-manager | grep -q Running
  args:
    chdir: "{{ awx_on_k3s_dir }}"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: operator_status
  until: operator_status.rc == 0
  retries: 30
  delay: 10
