---
all:
  children:
    awx_servers:
      hosts:
        awx_host:
          ansible_host: "{{ awx_host_address }}"
          ansible_user: "{{ awx_host_user }}"
          
          # SSH key authentication
          ansible_ssh_private_key_file: "{{ awx_host_ssh_key_file | default(omit) }}"
          
          # SSH password authentication 
          ansible_ssh_pass: "{{ awx_host_ssh_pass | default(omit) }}"
          ansible_become_pass: "{{ awx_host_become_pass | default(omit) }}"
